### ISSUE TITLE
Str addin issue

### ISSUE THREAD

**Issue by GegznaV** [AndriSignorell/DescToolsAddIns#2]
Add-in generates this code:
```r
> Str(iris)
Error in Str(iris) : could not find function "Str"
```
I expect addin to work out of the box.
The add-in should refer to a correct namespace, e.g., `DescTools::Str(iris)`

**Comment by GegznaV** [comment]
The same applies to the other addins like `Abstract()`, `Some()`, `Desc()`, ...

**Comment by facorread** [comment]
Hey, I was really hoping this package would make life easier for everyone; I get an error message that I imagine is related to this issue:

`> Str(a)
Error in Str(a) : unused argument (a)`

**Comment by AndriSignorell** [comment]
Done that, will be included in DescToolsAddIns 1.6.

**Comment by AndriSignorell** [comment]
This is fixed from my point of view, could you please check?

**Comment by AndriSignorell** [comment]
From my point of view done...
